[project]
name = 'backend'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.crowdfunding]
path = 'contracts/crowdfunding.clar'
clarity_version = 2
epoch = '2.5'

[contracts.crowdfunding-v2]
path = 'contracts/crowdfunding-v2.clar'
clarity_version = 2
epoch = '2.5'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
